## Changed E to how many matches can be made in total at the current time
WITH TEMP AS (SELECT PERSON.NAME as NAME, Person.COMPANY, INTEREST.PERSONNAME FROM PERSON INNER JOIN INTEREST ON Person.COMPANY = INTEREST.COMPANYNAME)
SELECT * FROM TEMP WHERE NAME != PERSONNAME
